services:
    polidog_blog_ddd.transaction_manager:
        class: Polidog\BlogDDDBundle\BlogTransactionManager
        arguments:
            - "@doctrine.orm.entity_manager"

    # Repository
    polidog_blog_ddd.repository.post_repository:
          class: Doctrine\Common\Persistence\ObjectRepository
          factory: [ '@doctrine.orm.entity_manager', 'getRepository']
          arguments:
              - Polidog\BlogDDDBundle\Entity\Post

    polidog_blog_ddd.repository.user_repository:
        class: Doctrine\Common\Persistence\ObjectRepository
        factory: [ '@doctrine.orm.entity_manager', 'getRepository']
        arguments:
            - Polidog\BlogDDDBundle\Entity\User

    # authenticator
    polidog_blog_ddd.security.authenticator.form_authenticator:
        class: Polidog\BlogDDDBundle\Security\Authenticator\FormAuthenticator
        arguments:
            - "@polidog_blog_ddd.authentication"

    # encoder
    polidog_blog_ddd.base_password_encoder:
        class: Symfony\Component\Security\Core\Encoder\PasswordEncoderInterface
        factory: ["@security.encoder_factory", getEncoder]
        arguments:
            - Polidog\BlogDDDBundle\Entity\User

    polidog_blog_ddd.password_encoder:
        class: Polidog\BlogDDDBundle\PasswordEncoder
        arguments:
            - "@polidog_blog_ddd.base_password_encoder"

    # spec
    polidog_blog_ddd.account.register_specification:
        class: Polidog\Blog\Model\Account\RegisterSpecification
        arguments:
            - "@polidog_blog_ddd.repository.user_repository"

    # App
    polidog_blog_ddd.use_case.add_post:
        class: Polidog\Blog\Application\UseCase\AddPost
        arguments:
            - "@polidog_blog_ddd.repository.post_repository"
            - "@polidog_blog_ddd.repository.user_repository"
            - "@polidog_blog_ddd.transaction_manager"

    polidog_blog_ddd.use_case.register_user:
        class: Polidog\Blog\Application\UseCase\RegisterUser
        arguments:
            - "@polidog_blog_ddd.repository.user_repository"
            - "@polidog_blog_ddd.account.register_specification"
            - "@polidog_blog_ddd.transaction_manager"
            - "@polidog_blog_ddd.password_encoder"

    polidog_blog_ddd.authentication:
        class: Polidog\Blog\Application\UseCase\Authentication
        arguments:
            - "@polidog_blog_ddd.repository.user_repository"
            - "@polidog_blog_ddd.password_encoder"

    polidog_blog_ddd.list_all_posts:
        class: Polidog\Blog\Application\UseCase\ListAllPosts
        arguments:
            - "@polidog_blog_ddd.repository.post_repository"

    polidog_blog_ddd.list_posts:
        class: Polidog\Blog\Application\UseCase\ListPosts
        arguments:
            - "@polidog_blog_ddd.repository.post_repository"

    polidog_blog_ddd.publish_post:
        class: Polidog\Blog\Application\UseCase\PublishPost
        arguments:
            - "@polidog_blog_ddd.repository.post_repository"

