# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:

    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        user_login:
            entity:
                class: Polidog\BlogDDDBundle\Entity\User
                property: email

    encoders:
        Polidog\BlogDDDBundle\Entity\User:
            algorithm: bcrypt
            cost: 12


    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        user:
            anonymous: ~
            pattern: ^/.*
            stateless: false
            logout:
                path: /logout
                target: /
            guard:
                authenticators:
                    - polidog_blog_ddd.security.authenticator.form_authenticator
            # activate different ways to authenticate

            # https://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate
            #http_basic: ~

            # https://symfony.com/doc/current/security/form_login_setup.html
            #form_login: ~
        main:
            anonymous: ~

    access_control:
        # user
        - { path: ^/mypage/.*, role: [ROLE_USER] }


